### ISSUE TITLE
 Why is the consumption calculated only by the RPM?

### ISSUE THREAD

**Issue by ghost** [TyKonKet/FS17_FuelUsageDisplay#24]
https://github.com/TyKonKet/FS17_FuelUsageDisplay/blob/master/src/specializations/betterFuelUsage.lua#L158

**Comment by TyKonKet** [comment]
Because in real life the consumption depends from hom many fuel is injected into the motor and the amount of fuel injected in the motor depends from the speed of the motor (aka RPM).
The gearbox emulates a real behaviour of rpm so if the gearbox is active I use RPM to calculate the fuel consumption.
This also prevents (and in most cases is the only solution) problems like #20 #19 #13 #15 #17

**Comment by ghost** [comment]
New stuff to discuss incoming
😁 

Edit:
There is a problem. Full Throttle in a fully opened clutch cause 100% fuel consumption.

**Comment by MasterGee** [comment]
Hi there,

the best way i.m.h.o is a table about all vehicles with the specific fuel consumption. For example the Fendt 939 Vario S4 has by 100% Rated Speed and 80% Load a specific fuel consumption from 248g/kwh.

Formula:
(CONSUMPTION * (Density of the fuel in g/cm³)) * 1000 / (KW of the VEHICLE)  = SPECIFIC-FUEL-CONSUMPTION

(CONSUMPTION * 0,85g/cm³) * 1000 / 287KW = 248g/KWh
= 83,74liter

------
100% Rated Speed and 80% Load = 248g/KWh
90% RS and 80%  Load = ca. 223  --> 248 * 0,9
90% RS and 40 % Load = ca. 315 --> 248*0,9 + 40% (original 274g/KWh)

Instead of a table maybe a standard value of 230-250g/KWh is nearly on the most vehicles.

**Comment by ghost** [comment]
If you need help collecting data, tell me.

http://www.dlg-test.de/tests/Fendt-939-Vario-S4_de_neu.pdf

**Comment by TyKonKet** [comment]
Currently the maximum fuel consumption is 250g/KWh with an extra 0%-25% based on motor running hours, so it's not too much wrong.
We should also consider that in FS the entire economy is boosted then if we want to balance a bit fuel costs we must at least double it.
What do you think guys?

**Comment by TyKonKet** [comment]
About the gearbox I was thinking about something like this:
RPM (0-1) + Load (0-1) / 2
Maybe this is the best solution, but only if the gearbox is active because by default the motor RPM are totally wrong and I can't use them for calculations.

**Comment by ghost** [comment]
> factor = RPM_factor * Load_factor

 ?

edit:

No screw this. Yours is better
😉 


Whats with https://github.com/TyKonKet/GearboxAddon ?

**Comment by TyKonKet** [comment]
> Whats with https://github.com/TyKonKet/GearboxAddon ?  

It's a fork of Gearbox

**Comment by ghost** [comment]
Yeah.. but why

**Comment by TyKonKet** [comment]
Translations 😄

**Comment by ghost** [comment]
Ok after a few hours of gameplay:

This solution is good.
#https://github.com/TyKonKet/FS17_FuelUsageDisplay/commit/1522a3c38cf91d861b300fef3789aa6c566520e1
