### ISSUE TITLE
Deceleration of machines

### ISSUE THREAD

**Issue by MPosp** [TyKonKet/FS17_FuelUsageDisplay#39]
Hello, I'm testing your mod and I'm mostly happy, it works nicely, but in two cases there was a problem, surprisingly the same. Two machines from ModHub, Claas Dominator 118SL and Mengele Garant 540/2 will slow to 1km / h if they activate one of the machine functions. In the case of a harvester, it is the launching of the cutter bar (B) or the throwing pipe (O), in the second case it is spillage on the silage pit (Ctrl-I).
Can this easily be solved by XML editing in both modes or in Better Fuel Usage, or is this a more complex issue?
Thank you in advance for your reply.

**Comment by TyKonKet** [comment]
Hi @MPosp , thanks for the report, this kind of issue happens because not all mods are configured in the same way, for this reason i've made this mod in a way that i can change it's behavior based on the single vehicle or implement.
For example, i can customize the behavior of BFU only for Claas Dominator 118SL.
So yes, i can solve those issues relatively easily, the "hardest" part is to understand what cause the problem.
Unluckly i can't test every vehicle and tool (default and mod) and reports like that helps me a lot :)

**Comment by MPosp** [comment]
Well, what did I describe as an incentive for a subsequent repair? I just looked at your mod and found a system of easy repairs, as you describe.
So if I run into another problem, can I just describe it as the previous two?

**Comment by TyKonKet** [comment]
Yes sure!
